### PR TITLE
create cell form templates notes

### PR DESCRIPTION
**Pull request by rgbkrk**
Initial notes for cell forms / cell form templates.

I took some liberties in terms of swapping `templates` for `cell-forms` in some areas. If it seems wrong, feel free to follow it up with a new PR!

cc @mpacer @willingc @mckev-amazon

### CODE REVIEW

**Comment by willingc** [comment]
Thanks @rgbkrk. Tossing in my two cents - I wonder if `jupyter template` would be better than `pip install` since we can add more logic to introspect the python environment than with pip. Just a thought...

**Comment by rgbkrk** [comment]
Yeah I like `jupyter template` better too. I included both since I was just copying what was on the whiteboard. We can delete the `pip` version here.

**Comment by mckev-amazon** [comment]
Just a quick update on this just to make sure you knew I haven't forgotten about this.  :-)

I think this would be a great candidate for running through the JEP process proposed [here](https://github.com/jupyter/enhancement-proposals/pull/29).  I can find an owner here to get the ball rolling.  @rgbkrk WDYT?

**Comment by rgbkrk** [comment]
Sounds great to me! I'm going to be less responsive for a few months with a baby about to be due, but I'm supportive of the cell forms moving forward. 😄

**Comment by mckev-amazon** [comment]
Just a heads up on this, my hands are a little full with the new JEP Process, and Dependency Management JEPs (still work in progress), so @PierreBrunelle (from Eider) is going to put together the JEP for the cell forms/templates feature, so we should expect a JEP pre-proposal for this feature relatively soon (this week or next).

**Pull request merged**
